repos:
  - repo: local
    hooks:
      - id: build
        name: build
        entry: just build
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: just test
        language: system
        pass_filenames: false
      - id: flake-checker
        name: flake-checker
        entry: flake-checker
        language: system
        pass_filenames: false
      - id: justfile
        name: justfile
        entry: just --fmt --unstable
        language: system
        pass_filenames: false
      - id: statix
        name: statix
        entry: statix fix
        language: system
        pass_filenames: false
      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        pass_filenames: false
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.5.1post1
    hooks:
      - id: pre-commit-update
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        args:
          - --fix
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types:
          - markdown
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/astro/deadnix
    rev: v1.2.1
    hooks:
      - id: deadnix
        args:
          - --edit
  - repo: https://github.com/lycheeverse/lychee.git
    rev: v0.15.1
    hooks:
      - id: lychee
        args:
          - --no-progress
          - .
        pass_filenames: false
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
