[project]
name = "dev-scripts"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "pre-commit-update>=0.5.1.post1",
]

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = ["pre-commit-update>=0.3.3.post1"]
