# Remove pdfs
@clean *search_term:
    ./scripts/clean.nu {{ search_term }}

# Compile pdfs
@compile *search_term:
    ./scripts/compile.nu {{ search_term }}

# Create new score
@create *args:
    ./scripts/create.nu {{ args }}

# Open <score> in $EDITOR and pdf viewer, recompiling on file changes
@edit *args:
    ./scripts/edit.nu {{ args }}

# Get info about scores
@info *search_term:
    ./scripts/info.nu {{ search_term }}

# Open pdfs
@open-pdf *search_term:
    ./scripts/open-pdf.nu {{ search_term }}

# View project settings
@settings *args:
    ./scripts/settings.nu {{ args }}

# View available templates
@templates *args:
    ./scripts/templates.nu {{ args }}

# Update dependencies and score LilyPond version
@update *help:
    ./scripts/update-deps.nu {{ help }}
