repos:
  - repo: local
    hooks:
      - id: build
        name: build
        entry: just build
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: just test
        language: system
        pass_filenames: false
