# Build dev environments
@build *args:
    ./scripts/build.nu {{ args }}

# Run an environment Justfile
@justfile *args:
    ./scripts/justfile.nu {{ args }}

# List available environments and files
@list *help:
    ./scripts/list.nu {{ help }}
